#add_newline = false

#[line_break]
#disabled = true

[package]
disabled = true

[python]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[lua]
disabled = true

[aws]
disabled = true
