#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

# autorun
[[ -z "$HLWM_LOADED" ]] && ~/.config/herbstluftwm/autorun &
hc emit_hook reload
#xsetroot -solid "#5A8E3A"

###---keys---###
# [[ -f "$HOME/.config/herbstluftwm/keys" ]] && source $HOME/.config/herbstluftwm/keys
source $HOME/.config/herbstluftwm/keys
###---theme---###
source $HOME/.config/herbstluftwm/theme

###---window Rules---###
source $HOME/.config/herbstluftwm/winRules

# find the panel
###---polybar---###
 # panel=~/.config/herbstluftwm/polybar/polybar.sh
 # [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 # for monitor in $(hc list_monitors | cut -d: -f1) ; do
     # # start it on each monitor
     # "$panel" "$monitor" &
 # done

###---dzen2---###
#panel=~/.config/herbstluftwm/panel.sh
panel=~/repos/herbstluftwm/polybar/polybar.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
   # # start it on each monitor
    "$panel" "$monitor" &
done

hc split vertical 0.6; hc remove
